create table Person (
    person_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(100) UNIQUE NOT NULL,
    year_of_born int CHECK (year_of_born >= 1900)
);

create table Book (
    book_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id int REFERENCES Person(person_id) ON DELETE SET NULL,
    title varchar(100),
    author varchar(100),
    year_of_publication int default 0,
    CHECK (year_of_publication >= 0 AND year_of_publication <= 2022)
);